export enum ActivityType {
  SIGN_UP = 'SIGN_UP',
  SIGN_IN = 'SIGN_IN',
  SIGN_OUT = 'SIGN_OUT',
  UPDATE_PASSWORD = 'UPDATE_PASSWORD',
  DELETE_ACCOUNT = 'DELETE_ACCOUNT',
  UPDATE_ACCOUNT = 'UPDATE_ACCOUNT',
  TEST = 'TEST',
  ASSIGN_ROLE = 'ASSIGN_ROLE',
  CHECK_PERMISSION = 'CHECK_PERMISSION',
  GET_CUSTOM_ROLES = 'GET_CUSTOM_ROLES',
  CREATE_ROLE = 'CREATE_ROLE',
  CREATE_PERMISSION = 'CREATE_PERMISSION',
  UPDATE_ROLE = 'UPDATE_ROLE',
  CANCEL_SUBSCRIPTION = 'CANCEL_SUBSCRIPTION',
  CALL_WEBHOOK = 'CALL_WEBHOOK',
  PAYMENT_RETRY = 'PAYMENT_RETRY'
}
